"use client";
import { FormEvent, useEffect, useState } from "react";
import { addEventDiscussion, addEventMedia, createEventInvite } from "../lib/api";

export function EventDestinationExperience({ eventId }: { eventId: number }) {
  const [token, setToken] = useState(""); const [message, setMessage] = useState(""); const [kind, setKind] = useState<"comment" | "question">("comment"); const [notice, setNotice] = useState("");
  const [media, setMedia] = useState({ type: "photo" as "photo" | "video", url: "", caption: "" }); const [email, setEmail] = useState("");
  useEffect(() => setToken(localStorage.getItem("aoa_rider_token") || ""), []);
  async function discuss(e: FormEvent) { e.preventDefault(); try { await addEventDiscussion(eventId, token, kind, message); setMessage(""); setNotice("Submitted for moderator approval."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to submit"); } }
  async function upload(e: FormEvent) { e.preventDefault(); try { await addEventMedia(eventId, token, media.type, media.url, media.caption); setMedia({ ...media, url: "", caption: "" }); setNotice("Media submitted for moderator approval."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to submit"); } }
  async function invite(e: FormEvent) { e.preventDefault(); try { const result = await createEventInvite(eventId, token, email); await navigator.clipboard.writeText(`${location.origin}${result.invite_url}`); setNotice("Private invite link copied."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to invite"); } }
  return <section className="destination-engagement dashboard-card"><div className="section-heading"><p>Ride together</p><h2>Questions, comments, media, and invites</h2></div><div className="destination-form-grid"><form onSubmit={discuss}><select value={kind} onChange={(e) => setKind(e.target.value as typeof kind)}><option value="comment">Comment</option><option value="question">Question</option></select><textarea required maxLength={2000} placeholder="Ask riders or share a tip" value={message} onChange={(e) => setMessage(e.target.value)}/><button>Submit for review</button></form><form onSubmit={upload}><select value={media.type} onChange={(e) => setMedia({ ...media, type: e.target.value as "photo" | "video" })}><option value="photo">Photo</option><option value="video">Video link</option></select><input required placeholder="Photo data/URL or HTTPS video URL" value={media.url} onChange={(e) => setMedia({ ...media, url: e.target.value })}/><input placeholder="Caption" value={media.caption} onChange={(e) => setMedia({ ...media, caption: e.target.value })}/><button>Upload for review</button></form><form onSubmit={invite}><input type="email" placeholder="Friend email (optional)" value={email} onChange={(e) => setEmail(e.target.value)}/><button>Create invite link</button></form></div>{notice ? <p aria-live="polite">{notice}</p> : null}</section>;
}
