"use client";

import { FormEvent, useEffect, useState } from "react";
import { createEventSource, getEventCandidates, getEventSources, getEventsIntelligence, reviewEventCandidate, runEventDiscovery, updateEventSource } from "../lib/api";
import type { EventCandidate, EventSource, EventsIntelligence } from "../lib/types";

export function EventsIntelligencePanel({ adminPassword }: { adminPassword: string }) {
  const [sources, setSources] = useState<EventSource[]>([]); const [candidates, setCandidates] = useState<EventCandidate[]>([]);
  const [summary, setSummary] = useState<EventsIntelligence | null>(null); const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ name: "", source_type: "official_event_calendar", base_url: "", feed_url: "", state: "KY", scan_frequency: "daily" });
  async function load() { const [nextSources, nextCandidates, nextSummary] = await Promise.all([getEventSources(adminPassword), getEventCandidates(adminPassword), getEventsIntelligence(adminPassword)]); setSources(nextSources); setCandidates(nextCandidates); setSummary(nextSummary); }
  useEffect(() => { if (adminPassword) load().catch(() => setNotice("Unable to load Events Intelligence.")); }, [adminPassword]);
  async function addSource(event: FormEvent) { event.preventDefault(); try { await createEventSource(form, adminPassword); setForm({ ...form, name: "", base_url: "", feed_url: "" }); await load(); setNotice("Source added inactive for admin review."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to add source."); } }
  async function toggle(source: EventSource, field: "is_active" | "is_trusted") { await updateEventSource(source.id, { [field]: !source[field] }, adminPassword); await load(); }
  async function scan(sourceId: number) { setNotice("Scanning approved source…"); await runEventDiscovery(sourceId, adminPassword); await load(); setNotice("Scan complete."); }
  async function review(candidate: EventCandidate, action: "approve" | "reject" | "ignore" | "merge") { const eventId = action === "merge" ? Number(window.prompt("Existing event ID", String(candidate.duplicate_event_id || ""))) : undefined; if (action === "merge" && !eventId) return; await reviewEventCandidate(candidate.id, { action, event_id: eventId, is_verified: false }, adminPassword); await load(); }
  return <section className="dashboard-card" aria-label="Events Intelligence">
    <div className="section-heading"><p>Automated discovery</p><h2>Events Intelligence</h2><span>Candidates never publish without an admin decision.</span></div>
    {summary ? <div className="admin-stats"><article><strong>{summary.new_candidates}</strong><span>New</span></article><article><strong>{summary.high_confidence}</strong><span>High confidence</span></article><article><strong>{summary.possible_duplicates}</strong><span>Duplicates</span></article><article><strong>{summary.possible_updates}</strong><span>Updates</span></article><article><strong>{summary.source_failures}</strong><span>Source failures</span></article></div> : null}
    <form onSubmit={addSource} className="admin-form"><h3>Add approved source</h3><input required placeholder="Source name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><select value={form.source_type} onChange={(e) => setForm({ ...form, source_type: e.target.value })}><option value="official_website">Official website</option><option value="official_event_calendar">Official calendar</option><option value="tourism_calendar">Tourism calendar</option><option value="rss">RSS/Atom</option><option value="ical">iCalendar</option><option value="public_api">Public API</option><option value="registration_platform">Registration platform</option></select><select value={form.state} onChange={(e) => setForm({ ...form, state: e.target.value })}>{["KY","WV","VA","TN","NC"].map((state) => <option key={state}>{state}</option>)}</select><input required type="url" placeholder="Public source URL" value={form.base_url} onChange={(e) => setForm({ ...form, base_url: e.target.value })}/><input type="url" placeholder="Optional feed URL" value={form.feed_url} onChange={(e) => setForm({ ...form, feed_url: e.target.value })}/><button type="submit">Add inactive source</button></form>
    <div className="admin-list"><h3>Trusted source registry</h3>{sources.length ? sources.map((source) => <article key={source.id}><div><strong>{source.name}</strong><p>{source.state} · {source.source_type} · {source.candidate_count} candidates · {source.success_rate ?? "—"}% success</p>{source.last_error ? <p className="error-message">{source.last_error}</p> : null}</div><div className="hero-actions"><button onClick={() => toggle(source, "is_trusted")}>{source.is_trusted ? "Untrust" : "Trust"}</button><button onClick={() => toggle(source, "is_active")}>{source.is_active ? "Deactivate" : "Activate"}</button><button disabled={!source.is_active} onClick={() => scan(source.id)}>Scan now</button></div></article>) : <p>No sources configured. Production starts with an empty registry.</p>}</div>
    <div className="admin-list"><h3>Candidate review queue</h3>{candidates.length ? candidates.map((candidate) => <article key={candidate.id}><div><strong>{candidate.title}</strong><p>{candidate.start_date || "Date needs review"} · {candidate.city || candidate.venue || candidate.state} · confidence {candidate.confidence_score}</p><p>{candidate.confidence_reasons.join(" · ")}</p>{candidate.duplicate_event_id ? <p>Possible match: event #{candidate.duplicate_event_id}</p> : null}</div><div className="hero-actions"><a href={candidate.source_url} target="_blank" rel="noreferrer">Source</a><button onClick={() => review(candidate, "approve")}>Approve new</button>{candidate.duplicate_event_id ? <button onClick={() => review(candidate, "merge")}>Merge</button> : null}<button onClick={() => review(candidate, "reject")}>Reject</button><button onClick={() => review(candidate, "ignore")}>Ignore</button></div></article>) : <p>No candidates waiting for review.</p>}</div>
    {notice ? <p aria-live="polite">{notice}</p> : null}
  </section>;
}
