"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { ExploreDestination } from "../lib/types";
import { AddExploreToTrip } from "./AddExploreToTrip";

const categoryLabels: Record<string, string> = { local_food:"Local Food", lodging:"Lodging", waterfalls:"Waterfalls", scenic_overlooks:"Scenic Overlooks", elk_viewing:"Elk Viewing", fishing:"Fishing", hiking:"Hiking", swimming:"Swimming", historic_sites:"Historic Sites", museums:"Museums", local_shops:"Local Shops", country_stores:"Country Stores", ice_cream_desserts:"Ice Cream & Desserts", family_activities:"Family Activities", campgrounds:"Campgrounds", parks:"Parks", events:"Events", fuel:"Fuel", repairs_recovery:"Repairs & Recovery", hospitals_urgent_care:"Hospitals & Urgent Care" };
const icons: Record<string,string> = { local_food:"🍴",lodging:"⌂",waterfalls:"≋",scenic_overlooks:"△",elk_viewing:"♢",fishing:"◁",hiking:"↟",swimming:"≈",historic_sites:"▥",museums:"▤",local_shops:"◇",country_stores:"▣",ice_cream_desserts:"●",family_activities:"★",campgrounds:"⌁",parks:"♧",events:"◆",fuel:"⛽",repairs_recovery:"⚒",hospitals_urgent_care:"+" };

export function ExplorePlaceholder({ item }: { item: ExploreDestination }) { return <div className="explore-placeholder" aria-label={`${item.name} placeholder`}><span>{icons[item.category] || "◆"}</span><small>Explore Appalachia</small><strong>{item.name}</strong></div>; }

export function ExploreBrowser({ destinations }: { destinations: ExploreDestination[] }) {
  const [q,setQ]=useState(""); const [state,setState]=useState(""); const [category,setCategory]=useState(""); const [family,setFamily]=useState(false); const [free,setFree]=useState(false); const [setting,setSetting]=useState("");
  const rows=useMemo(()=>destinations.filter((item)=>{ const text=`${item.name} ${item.city} ${item.county} ${item.state} ${item.short_description}`.toLowerCase(); return (!q||text.includes(q.toLowerCase()))&&(!state||item.state===state)&&(!category||item.category===category)&&(!family||item.family_friendly)&&(!free||item.free_admission)&&(!setting||(setting==="indoor"?item.indoor:item.outdoor)); }),[destinations,q,state,category,family,free,setting]);
  const states=Array.from(new Set(destinations.map((item)=>item.state).filter(Boolean))).sort();
  return <section className="explore-browser"><div className="explore-filters"><input aria-label="Search destinations" placeholder="Search place, city, county, or trail area" value={q} onChange={(e)=>setQ(e.target.value)}/><select aria-label="State" value={state} onChange={(e)=>setState(e.target.value)}><option value="">All states</option>{states.map((v)=><option key={v}>{v}</option>)}</select><select aria-label="Category" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="">All categories</option>{Object.entries(categoryLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select aria-label="Indoor or outdoor" value={setting} onChange={(e)=>setSetting(e.target.value)}><option value="">Indoor & outdoor</option><option value="indoor">Indoor</option><option value="outdoor">Outdoor</option></select><label><input type="checkbox" checked={family} onChange={(e)=>setFamily(e.target.checked)}/> Family friendly</label><label><input type="checkbox" checked={free} onChange={(e)=>setFree(e.target.checked)}/> Free</label></div><p className="explore-count">{rows.length} destinations</p>{rows.length?<div className="explore-grid">{rows.map((item)=><article className="explore-card" key={item.id}>{item.image_url?<img alt="" src={item.image_url}/>:<ExplorePlaceholder item={item}/>}<div><p className="eyebrow">{categoryLabels[item.category]||item.category}</p><h2>{item.name}</h2><p>{item.city}, {item.state}{item.distance_miles!=null?` · ${item.distance_miles} miles away`:""}</p><p>{item.short_description}</p><div className="listing-meta">{item.family_friendly?<span>Family friendly</span>:null}{item.veteran_owned?<span>Veteran owned</span>:null}{item.free_admission?<span>Free</span>:null}{item.verified?<span>Verified</span>:null}</div><div className="admin-actions"><AddExploreToTrip destination={item}/><Link href={`/explore/${item.slug}`}>View Details</Link>{item.latitude&&item.longitude?<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${item.latitude},${item.longitude}`}>Directions</a>:null}</div></div></article>)}</div>:<p className="empty-state">No approved destinations match these filters yet. Try a nearby city or suggest a place.</p>}</section>;
}
