import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { EventDestinationExperience } from "../../../../components/EventDestinationExperience";
import { EventEngagementPanel } from "../../../../components/EventEngagementPanel";
import { getEvent, getEventDestination } from "../../../../lib/api";

type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const event = await getEvent(slug); return { title: event ? `${event.title} | Appalachia Offroad` : "Ride Event", description: event?.description, openGraph: event ? { title: event.title, description: event.description, images: event.image_url ? [event.image_url] : [] } : undefined }; }
export default async function EventPage({ params }: Props) {
  const { slug } = await params; const destination = await getEventDestination(slug); if (!destination) notFound(); const { event, businesses, itinerary, weather, conditions, discussions, media } = destination;
  const groups = ["lodging", "food", "fuel", "repairs", "recovery", "wash", "supplies"];
  const mapQuery = event.latitude != null && event.longitude != null ? `${event.latitude},${event.longitude}` : `${event.venue} ${event.city} ${event.state}`;
  return <main className="page event-destination-page"><section className="page-hero compact"><p className="eyebrow">Verified event destination</p><h1>{event.title}</h1><p>{event.start_date}–{event.end_date} · {event.venue ? `${event.venue} · ` : ""}{event.city}, {event.state}</p><div className="listing-meta"><span>{event.is_verified ? "Verified" : "Approval pending"}</span><span>{event.category}</span><span>{event.difficulty.replaceAll("_", " ")}</span>{event.family_friendly != null ? <span>{event.family_friendly ? "Family friendly" : "Adult-focused"}</span> : null}{event.estimated_attendance ? <span>About {event.estimated_attendance.toLocaleString()} riders</span> : null}</div><div className="hero-actions">{event.registration_url ? <a href={event.registration_url}>Register</a> : null}<a href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(mapQuery)}`}>Navigate</a>{event.official_url ? <a href={event.official_url}>Official website</a> : null}</div></section>
    <section className="page-section"><article className="dashboard-card"><h2>Plan the event</h2><p>{event.description}</p><p><strong>Organizer:</strong> {event.organizer || "Not listed"}</p><p><strong>Vehicles:</strong> {event.vehicle_types.join(", ") || "Confirm with organizer"}</p><div className="hero-actions">{event.facebook_url ? <a href={event.facebook_url}>Facebook</a> : null}{event.instagram_url ? <a href={event.instagram_url}>Instagram</a> : null}</div></article><EventEngagementPanel event={event}/>
    <section className="dashboard-card"><div className="section-heading"><p>Forecast</p><h2>Weather at the event</h2></div>{weather.available ? <div className="weather-strip"><article><strong>{weather.current?.temperature_2m}°F</strong><span>Current</span></article>{(weather.daily?.time || []).slice(0, 4).map((day, index) => <article key={String(day)}><strong>{weather.daily?.temperature_2m_max?.[index]}° / {weather.daily?.temperature_2m_min?.[index]}°</strong><span>{String(day)} · {weather.daily?.precipitation_probability_max?.[index]}% rain</span></article>)}</div> : <p>{weather.message}</p>}</section>
    <section><div className="section-heading"><p>Stay, eat, fuel, repair</p><h2>Nearby trip planner</h2></div>{groups.map((group) => { const matches = businesses.filter((business) => business.group === group); return matches.length ? <div key={group} className="destination-group"><h3>{group[0].toUpperCase()+group.slice(1)}</h3><div className="destination-card-grid">{matches.map((business) => <article className={`dashboard-card ${business.is_sponsored ? "destination-sponsored" : ""}`} key={business.id}>{business.is_sponsored ? <span className="sponsor-label">{business.disclosure}</span> : null}{business.photo_url ? <img loading="lazy" src={business.photo_url} alt=""/> : null}<h4>{business.name}</h4><p>{business.distance_miles} miles · {business.rating ? `${business.rating}★` : "New listing"}</p><div className="hero-actions"><a href={`/business/${business.slug}`}>View</a>{business.has_booking ? <a href={`/business/${business.slug}#book`}>Book</a> : null}{business.phone ? <a href={`tel:${business.phone}`}>Call</a> : null}</div></article>)}</div></div> : null; })}{businesses.length === 0 ? <p className="empty-state">No approved nearby businesses yet.</p> : null}</section>
    <section className="dashboard-card"><div className="section-heading"><p>Friday through Sunday</p><h2>Suggested weekend itinerary</h2></div><div className="itinerary-grid">{itinerary.map((day) => <article key={day.day}><h3>{day.day}</h3><ol>{day.items.map((item, index) => <li key={`${item.label}-${index}`}>{item.business_slug ? <a href={`/business/${item.business_slug}`}>{item.label}</a> : item.label}</li>)}</ol></article>)}</div></section>
    <section className="dashboard-card"><div className="section-heading"><p>Ride status</p><h2>Trail conditions and hazards</h2></div>{conditions.length ? conditions.map((condition) => <article key={condition.id}><strong>{condition.type.replaceAll("_", " ")} · {condition.severity}</strong><p>{condition.trail}: {condition.note}</p></article>) : <p>No approved condition alerts for this event area.</p>}</section>
    <section className="dashboard-card"><h2>Rider questions and comments</h2>{discussions.length ? discussions.map((item) => <article key={item.id}><strong>{item.kind}</strong><p>{item.message}</p></article>) : <p>No approved discussion yet.</p>}<div className="destination-media-grid">{media.map((item) => item.type === "photo" ? <figure key={item.id}><img loading="lazy" src={item.url} alt={item.caption}/><figcaption>{item.caption}</figcaption></figure> : <a key={item.id} href={item.url}>Watch: {item.caption || "rider video"}</a>)}</div></section><EventDestinationExperience eventId={event.id}/><p className="field-help">Always confirm event, weather, trail, and business details before traveling.</p></section></main>;
}
