"""Add trusted event discovery sources, candidates, scans, and audit history."""
from alembic import op
import sqlalchemy as sa

revision = "0023_event_discovery"
down_revision = "0022_event_metrics_created_at_index"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("event_sources", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(180), nullable=False), sa.Column("source_type", sa.String(40), nullable=False), sa.Column("base_url", sa.Text(), nullable=False), sa.Column("feed_url", sa.Text(), nullable=False, server_default=""), sa.Column("state", sa.String(2), nullable=False), sa.Column("organizer_name", sa.String(180), nullable=False, server_default=""), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("is_trusted", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("scan_frequency", sa.String(30), nullable=False, server_default="daily"), sa.Column("last_scanned_at", sa.DateTime()), sa.Column("last_success_at", sa.DateTime()), sa.Column("last_error", sa.Text(), nullable=False, server_default=""), sa.Column("consecutive_failures", sa.Integer(), nullable=False, server_default="0"), sa.Column("scan_locked_at", sa.DateTime()), sa.Column("notes", sa.Text(), nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now()))
    for column in ("source_type", "state", "is_active", "is_trusted"): op.create_index(f"ix_event_sources_{column}", "event_sources", [column])
    op.create_table("event_candidates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_id", sa.Integer(), sa.ForeignKey("event_sources.id"), nullable=False), sa.Column("external_id", sa.String(240), nullable=False), sa.Column("source_url", sa.Text(), nullable=False), sa.Column("title", sa.String(180), nullable=False), sa.Column("organizer", sa.String(180), nullable=False, server_default=""), sa.Column("description", sa.Text(), nullable=False, server_default=""), sa.Column("state", sa.String(2), nullable=False), sa.Column("city", sa.String(120), nullable=False, server_default=""), sa.Column("venue", sa.String(180), nullable=False, server_default=""), sa.Column("address", sa.String(240), nullable=False, server_default=""), sa.Column("latitude", sa.Float()), sa.Column("longitude", sa.Float()), sa.Column("start_date", sa.Date()), sa.Column("end_date", sa.Date()), sa.Column("category", sa.String(80), nullable=False, server_default="group_ride"), sa.Column("vehicle_types", sa.JSON(), nullable=False, server_default="[]"), sa.Column("official_url", sa.Text(), nullable=False, server_default=""), sa.Column("registration_url", sa.Text(), nullable=False, server_default=""), sa.Column("facebook_url", sa.Text(), nullable=False, server_default=""), sa.Column("image_url", sa.Text(), nullable=False, server_default=""), sa.Column("raw_text", sa.Text(), nullable=False, server_default=""), sa.Column("raw_metadata_json", sa.JSON(), nullable=False, server_default="{}"), sa.Column("confidence_score", sa.Integer(), nullable=False, server_default="0"), sa.Column("confidence_reasons", sa.JSON(), nullable=False, server_default="[]"), sa.Column("duplicate_event_id", sa.Integer(), sa.ForeignKey("events.id")), sa.Column("change_detected", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("change_summary", sa.JSON(), nullable=False, server_default="{}"), sa.Column("status", sa.String(30), nullable=False, server_default="new"), sa.Column("first_seen_at", sa.DateTime(), server_default=sa.func.now()), sa.Column("last_seen_at", sa.DateTime(), server_default=sa.func.now()), sa.Column("reviewed_at", sa.DateTime()), sa.Column("reviewed_by", sa.String(120), nullable=False, server_default=""), sa.Column("admin_notes", sa.Text(), nullable=False, server_default=""), sa.UniqueConstraint("source_id", "external_id", name="uq_event_candidate_source_external"))
    for column in ("source_id", "title", "state", "start_date", "confidence_score", "duplicate_event_id", "status"): op.create_index(f"ix_event_candidates_{column}", "event_candidates", [column])
    op.create_table("event_source_scans", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_id", sa.Integer(), sa.ForeignKey("event_sources.id"), nullable=False), sa.Column("started_at", sa.DateTime(), server_default=sa.func.now()), sa.Column("completed_at", sa.DateTime()), sa.Column("status", sa.String(30), nullable=False, server_default="running"), sa.Column("items_seen", sa.Integer(), nullable=False, server_default="0"), sa.Column("candidates_created", sa.Integer(), nullable=False, server_default="0"), sa.Column("candidates_updated", sa.Integer(), nullable=False, server_default="0"), sa.Column("errors", sa.JSON(), nullable=False, server_default="[]"), sa.Column("response_status", sa.Integer()), sa.Column("duration_ms", sa.Integer(), nullable=False, server_default="0"))
    op.create_index("ix_event_source_scans_source_id", "event_source_scans", ["source_id"]); op.create_index("ix_event_source_scans_status", "event_source_scans", ["status"])
    op.create_table("event_verification_history", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("event_id", sa.Integer(), sa.ForeignKey("events.id"), nullable=False), sa.Column("candidate_id", sa.Integer(), sa.ForeignKey("event_candidates.id")), sa.Column("source_url", sa.Text(), nullable=False), sa.Column("admin_name", sa.String(120), nullable=False, server_default="admin"), sa.Column("action", sa.String(40), nullable=False), sa.Column("previous_values", sa.JSON(), nullable=False, server_default="{}"), sa.Column("new_values", sa.JSON(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()))
    for column in ("event_id", "candidate_id", "action", "created_at"): op.create_index(f"ix_event_verification_history_{column}", "event_verification_history", [column])

def downgrade() -> None:
    for table in ("event_verification_history", "event_source_scans", "event_candidates", "event_sources"): op.drop_table(table)
