import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getEvents } from "../../../lib/api";
import { rideAreas } from "../../../lib/sample-data";

const states: Record<string, { code: string; name: string }> = { kentucky: { code: "KY", name: "Kentucky" }, "west-virginia": { code: "WV", name: "West Virginia" }, virginia: { code: "VA", name: "Virginia" }, tennessee: { code: "TN", name: "Tennessee" }, "north-carolina": { code: "NC", name: "North Carolina" } };
type Props = { params: Promise<{ state: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const value = states[(await params).state]; return { title: value ? `${value.name} Off-Road Events & Rides` : "State rides", description: value ? `Verified upcoming ATV, UTV, Jeep and off-road events in ${value.name}.` : "" }; }
export default async function StateRides({ params }: Props) { const value = states[(await params).state]; if (!value) notFound(); const events = await getEvents({ state: value.code, verified: true }).catch(() => []); const areas = rideAreas.filter((area) => area.state === value.code || area.state === value.name); return <main className="page"><section className="page-hero compact"><p className="eyebrow">State ride guide</p><h1>{value.name} rides and events</h1><p>Verified upcoming events, featured trail areas, and planning links.</p></section><section className="page-section"><h2>Upcoming verified events</h2>{events.length ? events.map((event) => <article className="dashboard-card" key={event.id}><h3>{event.title}</h3><p>{event.start_date} • {event.city}</p><Link href={`/trail-talk/rides/${event.slug}`}>View ride</Link></article>) : <p className="empty-state">No verified upcoming events are listed for this state yet.</p>}<h2>Trail areas</h2>{areas.length ? areas.map((area) => <Link key={area.slug} href={`/ride-areas/${area.slug}`}>{area.name}</Link>) : <p className="empty-state">Trail-area guides are being verified.</p>}<div className="hero-actions"><Link href="/trail-talk">Full event calendar</Link><Link href="/trail-talk">Trail Talk</Link></div></section></main>; }
