import type { TrailCoordinate } from "./types";

export type HatfieldMcCoyTrailRoute = {
  areaSlug: string;
  trailName: string;
  segments: TrailCoordinate[][];
};

// Generated by scripts/import_hatfield_mccoy_kmz.py after downloading
// official Hatfield-McCoy GIS/KMZ data from Trails Heaven.
export const hatfieldMcCoyTrailRoutes: HatfieldMcCoyTrailRoute[] = [];
