import type { RideMapFeature } from "./types";

export const appalachianRiverGauges: RideMapFeature[] = [
  {
    id: "usgs-03209500",
    areaSlug: "hatfield-ky",
    areaName: "Hatfield",
    title: "Levisa Fork at Pikeville",
    layer: "river_level",
    latitude: 37.464268,
    longitude: -82.526263,
    summary: "Live discharge and gauge height",
    detail: "USGS monitoring location 03209500. Readings are provisional and must be combined with weather, hazards, skill, and agency guidance.",
    status: "USGS real-time gauge",
    usgsSiteId: "03209500",
    url: "https://waterdata.usgs.gov/monitoring-location/USGS-03209500/",
  },
  {
    id: "usgs-03527000",
    areaSlug: "spearhead-mountain-view-va",
    areaName: "Spearhead Mountain View",
    title: "Clinch River at Speers Ferry",
    layer: "river_level",
    latitude: 36.648,
    longitude: -82.747,
    summary: "Live discharge and gauge height",
    detail: "USGS monitoring location 03527000. Readings are provisional and are not a standalone safety rating.",
    status: "USGS real-time gauge",
    usgsSiteId: "03527000",
    url: "https://waterdata.usgs.gov/monitoring-location/USGS-03527000/",
  },
  {
    id: "usgs-03184500",
    areaSlug: "pocahontas-wv",
    areaName: "Pocahontas",
    title: "New River at Hinton",
    layer: "river_level",
    latitude: 37.6703,
    longitude: -80.8928,
    summary: "Live flow, height, and available temperature",
    detail: "USGS monitoring location 03184500. Readings are provisional and are not a standalone safety rating.",
    status: "USGS real-time gauge",
    usgsSiteId: "03184500",
    url: "https://waterdata.usgs.gov/monitoring-location/USGS-03184500/",
  },
  {
    id: "usgs-03198500",
    areaSlug: "big-coal-river-wv",
    areaName: "Big Coal River",
    title: "Big Coal River at Ashford",
    layer: "river_level",
    latitude: 38.1797,
    longitude: -81.7117,
    summary: "Live discharge and gauge height",
    detail: "USGS monitoring location 03198500. Readings are provisional and are not a standalone safety rating.",
    status: "USGS real-time gauge",
    usgsSiteId: "03198500",
    url: "https://waterdata.usgs.gov/monitoring-location/USGS-03198500/",
  },
];
