import type { Business, RideArea, Tier, TrailReview } from "./types";

export const categories = [
  { label: "Lodging", href: "/lodging", value: "lodging" },
  { label: "Food", href: "/?category=food", value: "food" },
  { label: "Rentals", href: "/?category=rentals", value: "rentals" },
  { label: "Repairs", href: "/?category=repairs", value: "repairs" },
  { label: "Fuel", href: "/?category=fuel", value: "fuel" },
  { label: "Deals", href: "/deals", value: "deals" },
] as const;

export const rideAreas: RideArea[] = [
  {
    slug: "rush-ky",
    name: "Rush",
    state: "Kentucky",
    locationQuery: "Rush",
    latitude: 38.33536,
    longitude: -82.78155,
    headline: "Northeast Kentucky ride-area anchor near US 60 and I-64.",
    description:
      "A useful planning base for riders coming through Boyd and Carter counties who want nearby lodging, fuel, supplies, food, and repair backup before heading into the weekend.",
    bestFor: ["Northeast Kentucky trips", "Easy highway access", "Fuel planning", "Weekend staging"],
    nearbyTowns: ["Rush", "Ashland", "Cannonsburg", "Grayson", "Catlettsburg"],
    checklist: ["Fuel and supplies", "Food stops", "Place to stay", "Repair backup"],
  },
  {
    slug: "inez-ky",
    name: "Inez",
    state: "Kentucky",
    locationQuery: "Inez",
    latitude: 37.8662,
    longitude: -82.5388,
    headline: "Eastern Kentucky basecamp with room for a full weekend plan.",
    description:
      "A practical starting point for riders who want lodging, fuel, food, and service stops close enough to keep the weekend simple.",
    bestFor: ["Weekend groups", "Cabin stays", "Local food stops", "Trailer-friendly planning"],
    nearbyTowns: ["Inez", "Louisa", "Paintsville", "Prestonsburg"],
    checklist: ["Place to stay", "Fuel and supplies", "Food stops", "Repair backup"],
  },
  {
    slug: "hatfield-ky",
    name: "Hatfield",
    state: "Kentucky",
    locationQuery: "Hatfield",
    latitude: 37.6126,
    longitude: -82.2793,
    headline: "A compact ride weekend area for food, rentals, and quick planning.",
    description:
      "Good for riders who want a simple launch point with meals, rentals, and lodging decisions handled before they arrive.",
    bestFor: ["UTV rentals", "Group meals", "First-time visitors", "Short weekend trips"],
    nearbyTowns: ["Hatfield", "Pikeville", "South Williamson", "Belfry"],
    checklist: ["Machine rental", "Food stops", "Place to stay", "Claim any deals"],
  },
  {
    slug: "matewan-wv",
    name: "Matewan",
    state: "West Virginia",
    locationQuery: "Matewan",
    latitude: 37.6223,
    longitude: -82.1571,
    headline: "Historic trail-town energy with fuel and supply stops nearby.",
    description:
      "A strong planning anchor for riders who want quick access to supplies, food, and a simple call list before heading out.",
    bestFor: ["Fuel stops", "Historic town visits", "Supply runs", "Day rides"],
    nearbyTowns: ["Matewan", "Williamson", "Delbarton", "Bramwell"],
    checklist: ["Fuel and supplies", "Food stops", "Repair backup", "Place to stay"],
  },
  {
    slug: "harlan-ky",
    name: "Harlan County",
    state: "Kentucky",
    locationQuery: "Harlan",
    latitude: 36.8431,
    longitude: -83.3218,
    headline: "Mountain riding basecamp for riders who want a rugged weekend.",
    description:
      "Built for groups that need lodging, fuel, repairs, and a backup plan before committing to bigger mountain days.",
    bestFor: ["Mountain views", "Advanced riders", "Long ride days", "Repair backup"],
    nearbyTowns: ["Harlan", "Evarts", "Cumberland", "Pineville"],
    checklist: ["Place to stay", "Repair backup", "Fuel and supplies", "Food stops"],
  },
  {
    slug: "royal-blue-tn",
    name: "Royal Blue / Brimstone",
    state: "Tennessee",
    locationQuery: "Royal Blue",
    latitude: 36.4237,
    longitude: -84.2577,
    headline: "A Tennessee ride-area anchor for long weekends and bigger groups.",
    description:
      "A destination-style planning area where riders often need lodging, supplies, food, and a clear weekend checklist.",
    bestFor: ["Large groups", "Long weekends", "Cabin planning", "Fuel and supply runs"],
    nearbyTowns: ["Pioneer", "Huntsville", "Oneida", "LaFollette"],
    checklist: ["Place to stay", "Fuel and supplies", "Food stops", "Machine rental"],
  },
  {
    slug: "black-mountain-ky",
    name: "Black Mountain",
    state: "Kentucky",
    locationQuery: "Black Mountain",
    latitude: 36.9143,
    longitude: -82.8954,
    headline: "A high-country ride plan for groups that want a serious trail weekend.",
    description:
      "A strong destination page for riders comparing where to stay, fuel, eat, and find repair support before the trip.",
    bestFor: ["Experienced riders", "Mountain terrain", "Scenic rides", "Backup repair planning"],
    nearbyTowns: ["Evarts", "Harlan", "Lynch", "Cumberland"],
    checklist: ["Repair backup", "Fuel and supplies", "Place to stay", "Food stops"],
  },
];

export const trailReviews: TrailReview[] = [
  {
    id: 1,
    areaSlug: "rush-ky",
    riderName: "Weekend group lead",
    rating: 5,
    rideDate: "Spring ride",
    machine: "UTV",
    difficulty: "Moderate",
    trailCondition: "Good access roads, easy staging, fuel planning matters.",
    comment:
      "Rush works well as a northeast Kentucky base. We liked being close to Ashland and Grayson for food, supplies, and backup plans.",
  },
  {
    id: 2,
    areaSlug: "rush-ky",
    riderName: "Family ride planner",
    rating: 4,
    rideDate: "Weekend trip",
    machine: "ATV",
    difficulty: "Easy",
    trailCondition: "Good for planning, check weather before hauling in.",
    comment:
      "Nice area to stage a low-stress weekend. The key is lining up lodging and fuel before everyone gets there.",
  },
  {
    id: 3,
    areaSlug: "inez-ky",
    riderName: "Cabin crew",
    rating: 5,
    rideDate: "Fall weekend",
    machine: "Side-by-side",
    difficulty: "Moderate",
    trailCondition: "Great weekend base with useful nearby towns.",
    comment:
      "Inez is a good anchor when you want the whole trip planned: cabin, food, fuel, and a repair backup just in case.",
  },
  {
    id: 4,
    areaSlug: "hatfield-ky",
    riderName: "First-time visitor",
    rating: 4,
    rideDate: "Summer ride",
    machine: "Rental UTV",
    difficulty: "Easy",
    trailCondition: "Simple to plan, good for food and rental needs.",
    comment:
      "Hatfield is a strong pick for new riders because the weekend can stay simple. Food and rental planning are the big wins.",
  },
  {
    id: 5,
    areaSlug: "matewan-wv",
    riderName: "Day ride crew",
    rating: 5,
    rideDate: "Saturday ride",
    machine: "ATV",
    difficulty: "Moderate",
    trailCondition: "Historic town stop, bring a fuel and supply plan.",
    comment:
      "Matewan has the trail-town feel riders like. We would build the day around fuel, lunch, and a clear call list.",
  },
  {
    id: 6,
    areaSlug: "harlan-ky",
    riderName: "Mountain weekend rider",
    rating: 5,
    rideDate: "Long weekend",
    machine: "UTV",
    difficulty: "Hard",
    trailCondition: "Rugged mountain riding, come prepared.",
    comment:
      "Harlan is where I want the backup plan handled early. Lodging, repairs, and fuel need to be sorted before the big ride days.",
  },
  {
    id: 7,
    areaSlug: "royal-blue-tn",
    riderName: "Large group organizer",
    rating: 4,
    rideDate: "Holiday weekend",
    machine: "Mixed group",
    difficulty: "Moderate",
    trailCondition: "Good for groups, planning ahead saves time.",
    comment:
      "Royal Blue and Brimstone are easier when one person has the checklist. Lodging and supply stops should be locked in first.",
  },
  {
    id: 8,
    areaSlug: "black-mountain-ky",
    riderName: "Experienced rider",
    rating: 5,
    rideDate: "Fall ride",
    machine: "UTV",
    difficulty: "Hard",
    trailCondition: "Scenic, serious riding with strong prep needs.",
    comment:
      "Black Mountain is worth the trip, but we treat it like a serious weekend. Bring a plan for repairs, weather, and fuel.",
  },
];

export const sampleBusinesses: Business[] = [
  {
    id: 1,
    name: "Rush Ridge Lodging Partner",
    slug: "rush-ridge-lodging-partner",
    category: "lodging",
    description:
      "Founding partner lodging spot for cabins, campgrounds, or hotels serving riders around Rush, Ashland, Cannonsburg, and Grayson.",
    phone: "(606) 000-0001",
    location: "Rush, KY",
    photo_url:
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1200&q=80",
    website_url: "",
    owner_email: "rush-lodging@example.com",
    owner_access_token: "demo-rush-lodging",
    listing_status: "approved",
    admin_notes: "",
    subscription_tier: "lodging_partner",
    subscription_status: "active",
    stripe_customer_id: "",
    stripe_subscription_id: "",
    is_approved: true,
    is_featured: true,
    view_clicks: 184,
    action_clicks: 42,
    deals: [
      {
        id: 1,
        title: "Founding lodging deal",
        code: "BASECAMP",
        description: "Use this slot for a cabin, campground, or hotel special for rider groups.",
        is_active: true,
        claim_clicks: 12,
      },
    ],
    campaigns: [],
    service_requests: [],
  },
  {
    id: 2,
    name: "Hatfield Rider Meal Partner",
    slug: "hatfield-rider-meal-partner",
    category: "food",
    description:
      "Founding partner food spot for restaurants, grills, and group-friendly stops serving hungry riders near Hatfield and South Williamson.",
    phone: "(606) 000-0002",
    location: "Hatfield, KY",
    photo_url:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80",
    website_url: "",
    owner_email: "hatfield-food@example.com",
    owner_access_token: "demo-hatfield-food",
    listing_status: "approved",
    admin_notes: "",
    subscription_tier: "monthly_sponsor",
    subscription_status: "active",
    stripe_customer_id: "",
    stripe_subscription_id: "",
    is_approved: true,
    is_featured: true,
    view_clicks: 261,
    action_clicks: 77,
    deals: [
      {
        id: 2,
        title: "Founding rider meal deal",
        code: "RIDELOCAL",
        description: "Use this slot for an opening-weekend meal special or group discount.",
        is_active: true,
        claim_clicks: 49,
      },
    ],
    campaigns: [
      {
        id: 1,
        business_id: 2,
        campaign_type: "monthly_sponsor",
        title: "Hatfield rider meal sponsor",
        description: "Featured food placement for riders planning weekends near Hatfield and Rush.",
        target_area: "Hatfield / Rush",
        monthly_budget: 149,
        status: "active",
        impressions: 0,
        clicks: 0,
      },
    ],
    service_requests: [],
  },
  {
    id: 3,
    name: "Inez ATV Rental Partner",
    slug: "inez-atv-rental-partner",
    category: "rentals",
    description:
      "Founding partner rental spot for ATV and UTV operators offering machines, helmets, pickup windows, and ride-area advice around Inez.",
    phone: "(606) 000-0003",
    location: "Inez, KY",
    photo_url:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    website_url: "",
    owner_email: "inez-rentals@example.com",
    owner_access_token: "demo-inez-rentals",
    listing_status: "approved",
    admin_notes: "",
    subscription_tier: "featured_partner",
    subscription_status: "active",
    stripe_customer_id: "",
    stripe_subscription_id: "",
    is_approved: true,
    is_featured: false,
    view_clicks: 129,
    action_clicks: 33,
    deals: [],
    campaigns: [],
    service_requests: [],
  },
  {
    id: 4,
    name: "Harlan Trail Repair Partner",
    slug: "harlan-trail-repair-partner",
    category: "repairs",
    description: "Founding partner repair spot for tires, belts, fluids, and emergency service support near Harlan, Evarts, and Black Mountain.",
    phone: "(606) 000-0004",
    location: "Harlan, KY",
    photo_url:
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=1200&q=80",
    website_url: "",
    owner_email: "harlan-repair@example.com",
    owner_access_token: "demo-harlan-repair",
    listing_status: "approved",
    admin_notes: "",
    subscription_tier: "local_business",
    subscription_status: "active",
    stripe_customer_id: "",
    stripe_subscription_id: "",
    is_approved: true,
    is_featured: false,
    view_clicks: 98,
    action_clicks: 24,
    deals: [],
    campaigns: [],
    service_requests: [],
  },
  {
    id: 5,
    name: "Matewan Fuel & Supply Partner",
    slug: "matewan-fuel-supply-partner",
    category: "fuel",
    description:
      "Founding partner fuel and supply spot for gas, ice, snacks, straps, gloves, and last-minute rider needs near Matewan and Williamson.",
    phone: "(606) 000-0005",
    location: "Matewan, WV",
    photo_url:
      "https://images.unsplash.com/photo-1541410965313-d53b3c16ef17?auto=format&fit=crop&w=1200&q=80",
    website_url: "",
    owner_email: "matewan-fuel@example.com",
    owner_access_token: "demo-matewan-fuel",
    listing_status: "approved",
    admin_notes: "",
    subscription_tier: "local_business",
    subscription_status: "active",
    stripe_customer_id: "",
    stripe_subscription_id: "",
    is_approved: true,
    is_featured: false,
    view_clicks: 72,
    action_clicks: 19,
    deals: [],
    campaigns: [],
    service_requests: [],
  },
];

export const partnerTiers: Tier[] = [
  {
    id: "cleaner_partner",
    name: "Cleaner Partner",
    price: "$29.99",
    description: "For cleaners who want unlimited lodging turnover opportunities.",
    features: ["Flat monthly fee", "No per-clean cut", "Unlimited cleanings", "Lodging request access"],
  },
  {
    id: "monthly_sponsor",
    name: "Monthly Sponsor",
    price: "$149",
    description: "For businesses that want monthly ride-area/category visibility.",
    features: ["Ride-area sponsor placement", "Category boost", "Deal visibility", "Campaign status tracking"],
  },
  {
    id: "local_business",
    name: "Local Business",
    price: "$29",
    description: "For food, fuel, repair, and service providers.",
    features: ["Marketplace listing", "Phone and location CTA", "Deal or coupon", "Basic click stats"],
  },
  {
    id: "lodging_partner",
    name: "Lodging Partner",
    price: "$59",
    description: "For cabins, campgrounds, hotels, and rider-friendly stays.",
    features: ["Everything in Local", "Lodging category placement", "Photo-forward listing", "Founding partner badge"],
  },
  {
    id: "featured_partner",
    name: "Featured Partner",
    price: "$99",
    description: "For businesses that want homepage and category priority.",
    features: ["Everything in Lodging", "Featured placement", "Priority admin review", "Expanded deal visibility"],
  },
];
