import type { RideMapFeature } from "./types";

const virginiaClinchSource = "https://dwr.virginia.gov/boating/access?find_by_locality=563";
const westVirginiaDistrict4Source = "https://wvdnr.gov/wp-content/uploads/2023/04/Pub_District4FishingGuide_DNR_WILD_digital.pdf";
const westVirginiaDistrict5Source = "https://wvdnr.gov/wp-content/uploads/2024/02/Pub_D5_FishingGuide_DNR_WILD_digital_rspreads.pdf";

export const appalachianWaterAccess: RideMapFeature[] = [
  {
    id: "levisa-fork-carry-down",
    areaSlug: "hatfield-ky",
    areaName: "Hatfield",
    title: "Levisa Fork carry-down",
    layer: "water_access",
    latitude: 37.4881,
    longitude: -82.5443,
    summary: "Kayak and canoe carry-down",
    detail: "Year-round, 24-hour carry-down access. No launch lanes or ramp surface; unpaved parking for 25 or fewer vehicles and no official parking area.",
    status: "No fee • Carry-down only",
    waterAccessType: "carry_down",
    amenities: ["Unpaved parking", "No fee", "Open 24 hours"],
    updatedAt: "Source checked July 12, 2026",
    url: "https://app.fw.ky.gov/fisheries/accesssitedetail.aspx?asid=501",
  },
  ...[
    ["Blackford Bridge", 36.9965, -81.9437, "Gravel access", "No constructed ramp"],
    ["Carterton", 36.9152, -82.2215, "Shoreline access", "Hand launch"],
    ["Cleveland Park Landing", 36.9408, -82.1569, "Concrete hand-carry ramp", "Barrier-free • 1 ramp"],
    ["Nash's Ford", 36.967, -82.079, "Shoreline access", "Hand launch"],
    ["Puckett's Hole", 36.9699, -82.0137, "Shoreline access", "Hand launch"],
  ].map(([name, latitude, longitude, accessType, status]) => ({
    id: `clinch-${String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    areaSlug: "spearhead-mountain-view-va",
    areaName: "Spearhead Mountain View",
    title: String(name),
    layer: "water_access" as const,
    latitude: Number(latitude),
    longitude: Number(longitude),
    summary: `Clinch River • ${accessType}`,
    detail: "Virginia DWR public boating or shoreline access point. Check current river level, posted site rules, and launch suitability before arrival.",
    status: String(status),
    waterAccessType: String(accessType).includes("Shoreline") ? "shoreline" as const : "carry_down" as const,
    amenities: String(name) === "Cleveland Park Landing" ? ["Barrier-free", "Concrete ramp"] : [],
    updatedAt: "Source checked July 12, 2026",
    url: virginiaClinchSource,
  })),
  ...[
    ["Cedar Branch", 37.5015, -80.8497],
    ["Indian Creek Campground", 37.5232, -80.85],
    ["Bull Falls", 37.5401, -80.9098],
    ["Bluestone Lake Tailwaters", 37.6438, -80.8838],
    ["Bellepoint", 37.6521, -80.8852],
    ["Sandstone Recreation Area", 37.7605, -80.9001],
    ["Meadow Creek Access", 37.8094, -80.9245],
  ].map(([name, latitude, longitude]) => ({
    id: `new-river-${String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    areaSlug: "pocahontas-wv",
    areaName: "Pocahontas",
    title: String(name),
    layer: "water_access" as const,
    latitude: Number(latitude),
    longitude: Number(longitude),
    summary: "New River boat access",
    detail: "West Virginia DNR-listed river access with parking. Confirm whether current conditions suit a trailered boat or hand-launched kayak before arrival.",
    status: "Public access • Parking listed",
    waterAccessType: "trailer" as const,
    amenities: ["Parking"],
    updatedAt: "Source checked July 12, 2026",
    url: westVirginiaDistrict4Source,
  })),
  ...[
    ["Racine", 37.9716, -81.5286],
    ["Madison", 38.0649, -81.5756],
    ["Danville", 38.0765, -81.5997],
    ["Water Ways Park", 38.1375, -81.6464],
    ["Lower Big Coal access", 38.1892, -81.722],
  ].map(([name, latitude, longitude]) => ({
    id: `big-coal-${String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    areaSlug: "big-coal-river-wv",
    areaName: "Big Coal River",
    title: String(name),
    layer: "water_access" as const,
    latitude: Number(latitude),
    longitude: Number(longitude),
    summary: "Big Coal River launch access",
    detail: "West Virginia DNR-listed river access. Review posted conditions and verify ramp or carry-down suitability for your watercraft.",
    status: "Public river access",
    waterAccessType: "trailer" as const,
    amenities: ["Parking"],
    updatedAt: "Source checked July 12, 2026",
    url: westVirginiaDistrict5Source,
  })),
];
