import type { RideMapFeature } from "./types";

export const appalachianWildlifeManagementAreas: RideMapFeature[] = [
  {
    id: "north-cumberland-wma",
    areaSlug: "royal-blue-tn",
    areaName: "Royal Blue / Brimstone",
    title: "North Cumberland WMA",
    layer: "wma",
    latitude: 36.38391,
    longitude: -84.25569,
    summary: "TWRA-managed public wildlife land",
    detail: "Approximately 205,000 acres across six management units. Hunting, fishing, wildlife viewing, camping, hiking, and OHV use are regulated; an NCWMA OHV permit or qualifying permit is required for trail riding.",
    status: "Check hunt dates, blaze-orange rules, closures, and unit-specific access",
    updatedAt: "Source checked July 12, 2026",
    url: "https://www.tn.gov/twra/wildlife-management-areas/east-tennessee-r4/north-cumberland-wma.html",
    amenities: ["Camping", "Fishing", "Hunting", "Wildlife viewing", "Designated OHV routes"],
  },
  {
    id: "redbird-wma",
    areaSlug: "redbird-crest-ky",
    areaName: "Redbird Crest",
    title: "Redbird Wildlife Management Area",
    layer: "wma",
    latitude: 37.14,
    longitude: -83.55,
    summary: "Kentucky public hunting and wildlife land",
    detail: "WMA access and activities vary by tract and season. Use Kentucky Fish and Wildlife's public-land search for current boundaries, hunting rules, parking, and permitted activities.",
    status: "Representative marker • Verify official boundary before entering",
    updatedAt: "Source checked July 12, 2026",
    url: "https://app.fw.ky.gov/Public_Lands_Search/",
    amenities: ["Hunting", "Fishing", "Hiking", "Wildlife viewing"],
  },
  {
    id: "fishtrap-lake-wma",
    areaSlug: "hatfield-ky",
    areaName: "Hatfield",
    title: "Fishtrap Lake WMA",
    layer: "wma",
    latitude: 37.43,
    longitude: -82.42,
    summary: "Kentucky wildlife and fishing access",
    detail: "Public-land access near Fishtrap Lake and the Levisa Fork. Check Kentucky's current WMA listing for boundary, activity, and seasonal restrictions.",
    status: "Representative marker • Verify official boundary before entering",
    updatedAt: "Source checked July 12, 2026",
    url: "https://app.fw.ky.gov/Public_Lands_Search/",
    amenities: ["Hunting", "Fishing", "Boat access", "Wildlife viewing"],
  },
  {
    id: "big-south-wma",
    areaSlug: "big-coal-river-wv",
    areaName: "Big Coal River",
    title: "Big South WMA",
    layer: "wma",
    latitude: 38.02,
    longitude: -81.69,
    summary: "West Virginia DNR wildlife management area",
    detail: "Use the official WVDNR map for boundaries, roads, gates, public access, and current hunting or fishing regulations.",
    status: "Representative marker • Agency map controls",
    updatedAt: "Source checked July 12, 2026",
    url: "https://wvdnr.gov/wp-content/uploads/2022/11/BigSouthWMA_11x17.pdf",
    amenities: ["Hunting", "Wildlife viewing"],
  },
  {
    id: "rd-bailey-wma",
    areaSlug: "pinnacle-creek-wv",
    areaName: "Pinnacle Creek",
    title: "R.D. Bailey Lake WMA",
    layer: "wma",
    latitude: 37.6,
    longitude: -81.82,
    summary: "West Virginia DNR wildlife management area",
    detail: "WMA surrounding R.D. Bailey Lake. Review the official map and current WVDNR regulations before hunting, fishing, boating, or using interior roads.",
    status: "Representative marker • Agency map controls",
    updatedAt: "Source checked July 12, 2026",
    url: "https://wvdnr.gov/wp-content/uploads/2022/11/RDBaileyWMA_11x17.pdf",
    amenities: ["Hunting", "Fishing", "Boating", "Wildlife viewing"],
  },
];
